### ISSUE TITLE
rogcat as a library

### ISSUE THREAD

**Issue by tekjar** [flxo/rogcat#16]
Hi. Is `rogcat` a wrapper over `logcat` binary or is it a port with more features? I want to write a log shipper for android. My service runs inside android and I need a way to read logs. Can `rogcat` be used for this purpose?

**Comment by flxo** [comment]
Hi. `rogcat` is mainly a wrapper that provides convenience features that the plain `logcat` doesn't have. It not intended to be used as a library and probably not very portable because it has tons of dependencies. I'm not sure if I fully understand what a `log shipper` is. Do you want to read the buffers and send it somewhere? This basically running `logcat` and read it's stdout. 

Is your service written in Rust? If yes you can get some inspiration:

If you need to parse the logcat format, have a look at the [parser](https://github.com/flxo/rogcat/blob/master/src/parser.rs). For calling and capturing locats output  see [runner.rs](https://github.com/flxo/rogcat/blob/master/src/runner.rs). 

The individual modules of `rogcat` are that small that it's not really been worth separating them into crates, but of course this is possible...

**Comment by tekjar** [comment]
> Do you want to read the buffers and send it somewhere?

Yeah

> This basically running logcat and read it's stdout.

Yeah. But I'm not sure of the costs of reading output from `logcat` vs reading from buffers directly.

**Comment by flxo** [comment]
This seems to be clarified. @tekjar comment if you disagree. :-)

**Comment by tekjar** [comment]
You clarified my question. Thanks :)
