### ISSUE TITLE
Crash loop with more than one device

### ISSUE THREAD

**Issue by steelbrain** [flxo/rogcat#17]
```
( )  -    error: more than one device/emulator
( )  -    - waiting for device -
( )  -    error: more than one device/emulator
( )  -    - waiting for device -
....
```

^ That's what I get when I start rogcat and have two androids with USB debugging enabled

Edit: I installed through `brew` and have version `0.2.15`

**Comment by flxo** [comment]
Thanks for the report.

`rogcat` is not crashing here. You probably ran `rogcat` without any arguments. In this mode the default is to restart `adb logcat` when it exits. I implemented that this way because you don't have to restart `rogcat` when the devices disables USB, reboots etc...

You can set `ANDROID_SERIAL` to  select one of the devices. The `-s` option of `adb` is handled in `rogcat` but could be added.

Detecting this case where `adb` complains about the device selection is not super easy to implement. The return code is `1` and so not usable and the first line from `stderr` would be needed to be checked.

Maybe adding some artificial delay between the `adb` invocations helps in this default case (The restart option is only set by default when no command is passed to `rogcat`.

Anyway you can also run `adb logcat | rogcat -` or `rogcat "adb logcat"` to stop after the first attempt.

**Comment by flxo** [comment]
Think this done. Reopen if not. Cheers.
